apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: easyclaim-backend
  template:
    metadata:
      name: easyclaim-backend
      labels:
        name: easyclaim-backend
    spec:
      containers:
        - name:  easyclaim-backend
          image: vigneshsweekaran/easyclaim-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: "/config"
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "400m"
      volumes:
      - name: config-volume
        configMap:
          name: easyclaim-backend
          items:
          - key: application
            path: application.properties

---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
data:
  application: |-
    spring.datasource.url=jdbc:mysql://mysql:3306/test
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
apiVersion: v1
kind: Service
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    name: easyclaim-backend
